### ISSUE TITLE
JSON file is still useful

### ISSUE THREAD

**Issue by EvanBalster** [andreineculau/http-status-codes-json#4]
I needed a JSON file mapping status codes to their normative names for a project written in TiddlyWiki.  Had to dig back through this repository's history for this deleted file:  https://github.com/andreineculau/http-status-codes-json/blob/7c9660e4a812ec66eafc40ab7400511f85d3b315/http_status_codes.json

Might be helpful to others to restore just that file or put it into a gist.

**Comment by andreineculau** [comment]
Hi! Is there anything missing in https://github.com/for-GET/know-your-http-well/blob/master/json/status-codes.json ?
I can understand that one needs to filter out "category" entries, with status code 1xx 2xx etc, and to keep only the `phrase` property, but... potato-potato, right?

**Comment by andreineculau** [comment]
I'll better close this issue and archive this repo. Please open an issue in https://github.com/for-GET/know-your-http-well if you want to continue this thread. Thanks for understanding 🙏
